//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SERP.Core.Entities {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ValidaionMessage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ValidaionMessage() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SERP.Core.Entities.ValidaionMessage", typeof(ValidaionMessage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Academic End Date is required.
        /// </summary>
        public static string AcademicEndDate {
            get {
                return ResourceManager.GetString("AcademicEndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Academic Start Date is required.
        /// </summary>
        public static string AcademicStartDate {
            get {
                return ResourceManager.GetString("AcademicStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Academic name is required..
        /// </summary>
        public static string AcademinName {
            get {
                return ResourceManager.GetString("AcademinName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fine Amount is required..
        /// </summary>
        public static string LibraryFineAmount {
            get {
                return ResourceManager.GetString("LibraryFineAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issue Days is required..
        /// </summary>
        public static string LibrarySettingIssueDays {
            get {
                return ResourceManager.GetString("LibrarySettingIssueDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issue Time is required..
        /// </summary>
        public static string LibrarySettingIssueTimes {
            get {
                return ResourceManager.GetString("LibrarySettingIssueTimes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Type is required..
        /// </summary>
        public static string LibrarySettingUserType {
            get {
                return ResourceManager.GetString("LibrarySettingUserType", resourceCulture);
            }
        }
    }
}
